use super::super::super::super::StageDefaults;
use super::super::super::super::StageDownloadDefaults;
use super::super::super::super::StageWorkUnitDefaults;
use serde_json::json;

pub(in crate::store::helpers::defaults) fn development() -> StageDefaults {
    StageDefaults {
        objective: "完成前后端需求分析、任务拆分、Git/GitHub 协作、编码审查循环、稳定预览与交付归档",
        input_contexts: vec![
            "前端需求分析：页面清单、路由表、组件拆分、状态依赖、API 依赖、frontend-tasks.md",
            "后端需求分析：接口契约、数据模型、模块拆分、错误码、部署配置、backend-tasks.md",
            "任务拆分：前后端各自形成可执行任务包，边界与依赖同步冻结",
            "Git/GitHub：agent/* 开发分支合入 develop，必要时同步 GitHub 仓库与 PR 状态",
            "稳定预览：只有 develop 验证通过后才能推进 preview，用户稳定预览只指向 preview",
            "编码循环：编码 -> Code Review -> 修复 Review -> 测试 -> 继续编码，直到完成标准闭环",
            "交付归档：构建产物、接口文档、预览记录、审查记录、测试报告与最终归档都要可追踪",
        ],
        step_progress: json!([
            {"title":"前后端需求分析", "status":"running"},
            {"title":"任务拆分与接口契约冻结", "status":"queued"},
            {"title":"Git/GitHub 分支策略确认", "status":"queued"},
            {"title":"前端编码 -> Review -> 修复 -> 测试", "status":"queued"},
            {"title":"后端编码 -> Review -> 修复 -> 测试", "status":"queued"},
            {"title":"develop 集成验证", "status":"queued"},
            {"title":"preview 稳定预览发布", "status":"queued"},
            {"title":"交付归档", "status":"queued"}
        ]),
        risk_items: vec!["接口契约未冻结会导致前后端返工", "develop 未验证直接预览会破坏用户稳定访问", "Code Review 修复未闭环会积累缺陷", "GitHub 仓库同步失败会影响源代码归档"],
        event_flow: vec![
            "生成前后端需求分析",
            "拆分任务并冻结契约",
            "创建 agent 开发分支并同步 GitHub",
            "执行编码与 Code Review 循环",
            "合入 develop 并集成验证",
            "推进 preview 稳定预览",
            "打包归档可下载产物",
        ],
        downloads: vec![
            StageDownloadDefaults {
                id: "frontend-tasks",
                title: "前端任务拆分",
                category: "stage_snapshot",
                availability: "pending",
                file_path: None,
                updated_at_ms: None,
                content_type: Some("text/markdown"),
            },
            StageDownloadDefaults {
                id: "backend-tasks",
                title: "后端任务拆分",
                category: "stage_snapshot",
                availability: "pending",
                file_path: None,
                updated_at_ms: None,
                content_type: Some("text/markdown"),
            },
            StageDownloadDefaults {
                id: "git-github-plan",
                title: "Git/GitHub 协作记录",
                category: "audit_archive",
                availability: "pending",
                file_path: None,
                updated_at_ms: None,
                content_type: Some("text/markdown"),
            },
            StageDownloadDefaults {
                id: "stable-preview",
                title: "稳定预览记录",
                category: "stage_snapshot",
                availability: "pending",
                file_path: None,
                updated_at_ms: None,
                content_type: Some("text/markdown"),
            },
            StageDownloadDefaults {
                id: "code-review-log",
                title: "Code Review 记录",
                category: "audit_archive",
                availability: "pending",
                file_path: None,
                updated_at_ms: None,
                content_type: Some("text/markdown"),
            },
            StageDownloadDefaults {
                id: "test-report",
                title: "测试报告",
                category: "audit_archive",
                availability: "pending",
                file_path: None,
                updated_at_ms: None,
                content_type: Some("text/markdown"),
            },
            StageDownloadDefaults {
                id: "delivery-archive",
                title: "交付归档",
                category: "audit_archive",
                availability: "pending",
                file_path: None,
                updated_at_ms: None,
                content_type: Some("application/zip"),
            },
        ],
        work_units: vec![
            StageWorkUnitDefaults {
                id: "requirement-analysis",
                title: "前后端需求分析",
                agent_role: "需求分析 Agent",
                status: "running",
                progress: 0.35,
                depends_on: vec![],
                current_output: Some("需求拆分草稿"),
                next_step: "冻结需求边界后生成任务拆分",
            },
            StageWorkUnitDefaults {
                id: "api-contract",
                title: "接口契约与架构选择",
                agent_role: "后端规划 Agent",
                status: "blocked",
                progress: 0.0,
                depends_on: vec!["requirement-analysis"],
                current_output: None,
                next_step: "等待需求分析完成",
            },
            StageWorkUnitDefaults {
                id: "frontend-task-split",
                title: "前端任务拆分",
                agent_role: "前端规划 Agent",
                status: "blocked",
                progress: 0.0,
                depends_on: vec!["requirement-analysis", "api-contract"],
                current_output: None,
                next_step: "等待接口契约后生成页面与组件任务",
            },
            StageWorkUnitDefaults {
                id: "backend-task-split",
                title: "后端任务拆分",
                agent_role: "后端规划 Agent",
                status: "blocked",
                progress: 0.0,
                depends_on: vec!["requirement-analysis", "api-contract"],
                current_output: None,
                next_step: "等待接口契约后生成模块与数据任务",
            },
            StageWorkUnitDefaults {
                id: "implementation-loop",
                title: "编码与 Code Review 循环",
                agent_role: "实现与审查 Agent",
                status: "blocked",
                progress: 0.0,
                depends_on: vec!["frontend-task-split", "backend-task-split"],
                current_output: None,
                next_step: "等待任务拆分完成后进入编码循环",
            },
            StageWorkUnitDefaults {
                id: "stable-preview-delivery",
                title: "稳定预览与交付归档",
                agent_role: "集成验证 Agent",
                status: "blocked",
                progress: 0.0,
                depends_on: vec!["implementation-loop"],
                current_output: None,
                next_step: "等待编码测试通过后推进 preview 并归档",
            },
        ],
    }
}
