"""Pluggable document-driven coding providers.

The default provider integrates the official OpenSpec Codex skills generated by
`openspec init --tools codex`. It does not reimplement OpenSpec command
semantics; it loads the generated skill instructions and asks the coding LLM to
execute those instructions for each planned task.
"""

from __future__ import annotations

import json
import os
import platform
import shutil
import subprocess
import tarfile
import urllib.request
import zipfile
from collections.abc import Awaitable, Callable, Mapping
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Protocol

from langchain_core.messages import HumanMessage, SystemMessage

from ..config import ModelConfig
from ..llm import create_llm
from ..models import CodingContext
from ..retry import retry_async
from ..text_tools import deduped_string_list as _string_list
from ..tracing import build_trace_config

OPENSPEC_FLOW_STEPS: dict[str, str] = {
    "bootstrap": "正在初始化 OpenSpec 环境",
    "propose": "正在使用 OpenSpec 模式生成提案",
    "docs": "正在使用 OpenSpec 模式生成文档",
    "review": "正在使用 OpenSpec 模式评审文档",
    "revise": "正在使用 OpenSpec 模式修订文档",
    "apply": "正在使用 OpenSpec 模式执行实现",
    "archive": "正在使用 OpenSpec 模式归档任务",
    "complete": "OpenSpec 模式任务已完成",
}


class CodingProvider(Protocol):
    async def run(
        self,
        *,
        ctx: CodingContext,
        cfg: ModelConfig,
        tasks: list[dict[str, Any]],
    ) -> dict[str, Any]:
        """Return coding narrative and provider-specific task artifacts."""


class LegacyCodingProvider:
    """Compatibility provider for non-OpenSpec coding modes."""

    async def run(
        self,
        *,
        ctx: CodingContext,
        cfg: ModelConfig,
        tasks: list[dict[str, Any]],
    ) -> dict[str, Any]:
        task_breakdown_text = json.dumps(ctx.task_breakdown, ensure_ascii=False)
        coding_plan_text = json.dumps(tasks, ensure_ascii=False)
        from ..prompts import coding_agent_system_prompt, coding_agent_user_prompt

        llm = create_llm(cfg, max_tokens=4000, streaming=True)
        messages = [
            SystemMessage(content=coding_agent_system_prompt()),
            HumanMessage(
                content=coding_agent_user_prompt(
                    ctx.project_name,
                    task_breakdown_text,
                    coding_plan_text,
                )
            ),
        ]

        full_reply = ""
        deltas: list[str] = []

        async def _stream() -> None:
            nonlocal full_reply, deltas
            full_reply = ""
            deltas = []
            async for chunk in llm.astream(
                messages,
                config=build_trace_config(
                    "coding_agent",
                    "coding",
                    ctx,
                    prompt_keys=["coding.agent.system", "coding.agent.user"],
                ),
            ):
                delta = chunk.content
                if delta:
                    full_reply += delta
                    deltas.append(delta)

        await retry_async(_stream)
        return {"coding_reply": full_reply, "deltas": deltas, "openspec_tasks": []}


class OpenSpecSkillProvider:
    """Run coding tasks through the official OpenSpec skill artifacts."""

    def __init__(
        self,
        *,
        skill_root: Path | None = None,
        project_root: Path | None = None,
        max_review_iterations: int = 3,
    ) -> None:
        self.skill_root = skill_root
        self.project_root = project_root
        self.max_review_iterations = max_review_iterations

    async def run(
        self,
        *,
        ctx: CodingContext,
        cfg: ModelConfig,
        tasks: list[dict[str, Any]],
    ) -> dict[str, Any]:
        project_root = _resolve_project_root(self.project_root)
        deltas: list[str] = [_openspec_event("bootstrap")]
        skills = _OpenSpecSkills.load(self.skill_root or _ensure_openspec_ready(project_root))
        task_results: list[dict[str, Any]] = []
        replies: list[str] = []

        for task in tasks:
            result = await self._run_one_task(ctx, cfg, skills, task, project_root)
            task_results.append(result)
            replies.append(str(result.get("apply_reply") or ""))
            deltas.extend(_string_list(result.get("events"), 20, 512))

        return {
            "coding_reply": "\n\n".join(reply for reply in replies if reply.strip()),
            "deltas": deltas,
            "openspec_tasks": task_results,
        }

    async def _run_one_task(
        self,
        ctx: CodingContext,
        cfg: ModelConfig,
        skills: "_OpenSpecSkills",
        task: Mapping[str, Any],
        project_root: Path,
    ) -> dict[str, Any]:
        events: list[str] = []
        events.append(_openspec_event("propose", task))
        proposal = await _json_llm(
            cfg,
            ctx,
            run_name="openspec_propose",
            system=skills.propose,
            user=_propose_prompt(ctx, task),
        )
        events.append(_openspec_event("docs", task))
        docs = _normalize_docs(proposal)
        change_dir = _write_change_docs(project_root, docs)
        review_iterations = 0
        review_result: dict[str, Any] = {"approved": False, "summary": ""}

        while review_iterations < self.max_review_iterations:
            review_iterations += 1
            events.append(_openspec_event("review", task, iteration=review_iterations))
            review_result = await _json_llm(
                cfg,
                ctx,
                run_name="openspec_review",
                system=_OPENSPEC_REVIEW_SYSTEM,
                user=_review_prompt(ctx, task, docs),
            )
            if bool(review_result.get("approved")):
                break
            events.append(_openspec_event("revise", task, iteration=review_iterations))
            docs = _normalize_docs(
                await _json_llm(
                    cfg,
                    ctx,
                    run_name="openspec_revise",
                    system=skills.propose,
                    user=_revise_prompt(ctx, task, docs, review_result),
                )
            )
            events.append(_openspec_event("docs", task))
            change_dir = _write_change_docs(project_root, docs)

        if not bool(review_result.get("approved")):
            task_title = str(task.get("title") or task.get("id") or "OpenSpec task")
            raise RuntimeError(
                f"OpenSpec 文档评审达到上限（{self.max_review_iterations} 次）仍未通过：{task_title}"
            )

        events.append(_openspec_event("apply", task))
        apply_reply = await _text_llm(
            cfg,
            ctx,
            run_name="openspec_apply",
            system=skills.apply,
            user=_apply_prompt(ctx, task, docs),
        )
        events.append(_openspec_event("archive", task))
        archive_note = await _text_llm(
            cfg,
            ctx,
            run_name="openspec_archive",
            system=skills.archive,
            user=_archive_prompt(ctx, task, docs),
        )
        archive_dir = _archive_change_docs(project_root, docs, archive_note)
        events.append(_openspec_event("complete", task))

        return {
            "task_id": str(task.get("id") or ""),
            "title": str(task.get("title") or ""),
            "change_id": str(docs.get("change_id") or task.get("id") or ""),
            "change_dir": str(change_dir),
            "archive_dir": str(archive_dir),
            "proposal_md": docs["proposal_md"],
            "design_md": docs["design_md"],
            "tasks_md": docs["tasks_md"],
            "review_iterations": review_iterations,
            "review_result": review_result,
            "apply_reply": apply_reply,
            "archive_note": archive_note,
            "archived": True,
            "events": events,
        }


class _OpenSpecSkills:
    def __init__(self, propose: str, apply: str, archive: str) -> None:
        self.propose = propose
        self.apply = apply
        self.archive = archive

    @classmethod
    def load(cls, skill_root: Path | None = None) -> "_OpenSpecSkills":
        roots = [skill_root] if skill_root else _candidate_skill_roots()
        propose = _read_skill(roots, "openspec-propose")
        apply = _read_skill(roots, "openspec-apply-change")
        archive = _read_skill(roots, "openspec-archive-change")
        return cls(propose=propose, apply=apply, archive=archive)


def provider_from_env() -> CodingProvider:
    provider = os.environ.get("AUTODEV_CODING_PROVIDER", "openspec").strip().lower()
    if provider in {"legacy", "plain"}:
        return LegacyCodingProvider()
    if provider in {"openspec", "open-spec", ""}:
        return OpenSpecSkillProvider()
    raise RuntimeError(f"未知 coding provider：{provider}")


def _openspec_event(
    step: str,
    task: Mapping[str, Any] | None = None,
    *,
    iteration: int | None = None,
) -> str:
    label = OPENSPEC_FLOW_STEPS.get(step, step)
    suffix = ""
    if task:
        title = str(task.get("title") or task.get("id") or "").strip()
        if title:
            suffix += f"：{title[:80]}"
    if iteration is not None:
        suffix += f"（第 {iteration} 次）"
    return f"coding: {label}{suffix}"


def _candidate_skill_roots() -> list[Path]:
    roots: list[Path] = []
    for base in _project_roots():
        roots.append(base / ".codex" / "skills")
    codex_home = os.environ.get("CODEX_HOME")
    roots.append(Path(codex_home).expanduser() / "skills" if codex_home else Path.home() / ".codex" / "skills")
    return roots


def _resolve_project_root(configured: Path | None = None) -> Path:
    if configured is not None:
        return configured.expanduser().resolve()
    env_root = os.environ.get("AUTODEV_PROJECT_ROOT", "").strip()
    if env_root:
        return Path(env_root).expanduser().resolve()
    return Path.cwd().resolve()


def _ensure_openspec_ready(project_root: Path) -> Path:
    existing_skill_root = _find_project_skill_root(project_root)
    if existing_skill_root is not None:
        return existing_skill_root

    env = _openspec_env()
    openspec_bin = _ensure_openspec_cli(env)
    _run_openspec_init(openspec_bin, project_root, env)

    skill_root = _find_project_skill_root(project_root)
    if skill_root is None:
        raise RuntimeError(
            "OpenSpec 已安装但未生成 Codex skill。请检查 openspec init --tools codex --profile core 的输出。"
        )
    return skill_root


def _find_project_skill_root(project_root: Path) -> Path | None:
    root = project_root / ".codex" / "skills"
    required = [
        "openspec-propose",
        "openspec-apply-change",
        "openspec-archive-change",
    ]
    if all(any(root.glob(f"{name}*/SKILL.md")) for name in required):
        return root
    return None


def _openspec_env() -> dict[str, str]:
    env = os.environ.copy()
    env["OPENSPEC_TELEMETRY"] = "0"
    env["DO_NOT_TRACK"] = "1"
    tools_bin = _tools_bin_dir()
    env["PATH"] = f"{tools_bin}{os.pathsep}{env.get('PATH', '')}"
    return env


def _ensure_openspec_cli(env: dict[str, str]) -> Path:
    existing = shutil.which("openspec", path=env.get("PATH"))
    if existing:
        return Path(existing)
    _ensure_node_runtime(env)
    npm = shutil.which("npm", path=env.get("PATH"))
    if not npm:
        raise RuntimeError("无法找到 npm，OpenSpec 自动安装失败。")
    subprocess.run(
        [npm, "install", "-g", "@fission-ai/openspec@latest", "--prefix", str(_npm_prefix())],
        check=True,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        timeout=300,
    )
    installed = shutil.which("openspec", path=env.get("PATH"))
    if not installed:
        raise RuntimeError("OpenSpec 安装完成但未找到 openspec 可执行文件。")
    return Path(installed)


def _ensure_node_runtime(env: dict[str, str]) -> None:
    node = shutil.which("node", path=env.get("PATH"))
    npm = shutil.which("npm", path=env.get("PATH"))
    if node and npm and _node_version_ok(node):
        return
    _install_node_runtime()
    env["PATH"] = f"{_node_bin_dir()}{os.pathsep}{env.get('PATH', '')}"
    node = shutil.which("node", path=env.get("PATH"))
    npm = shutil.which("npm", path=env.get("PATH"))
    if not node or not npm or not _node_version_ok(node):
        raise RuntimeError("Node.js 自动安装失败，OpenSpec 需要 Node.js 20.19.0 或更高版本。")


def _node_version_ok(node_bin: str) -> bool:
    try:
        proc = subprocess.run(
            [node_bin, "--version"],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=10,
        )
    except (subprocess.SubprocessError, OSError):
        return False
    version = proc.stdout.strip().lstrip("v")
    parts = [int(part) for part in version.split(".")[:3] if part.isdigit()]
    return tuple(parts + [0] * (3 - len(parts))) >= (20, 19, 0)


def _install_node_runtime() -> None:
    node_dir = _node_install_dir()
    if _node_bin_dir().exists():
        return
    node_dir.mkdir(parents=True, exist_ok=True)
    version = os.environ.get("AUTODEV_NODE_VERSION", "v22.12.0").strip()
    archive_name = _node_archive_name(version)
    url = f"https://nodejs.org/dist/{version}/{archive_name}"
    download_path = node_dir / archive_name
    urllib.request.urlretrieve(url, download_path)
    if archive_name.endswith(".zip"):
        with zipfile.ZipFile(download_path) as archive:
            archive.extractall(node_dir)
    else:
        with tarfile.open(download_path) as archive:
            archive.extractall(node_dir)


def _node_archive_name(version: str) -> str:
    system = platform.system().lower()
    machine = platform.machine().lower()
    if system == "darwin":
        os_name = "darwin"
    elif system == "linux":
        os_name = "linux"
    elif system == "windows":
        os_name = "win"
    else:
        raise RuntimeError(f"不支持自动安装 Node.js 的系统：{system}")
    if machine in {"arm64", "aarch64"}:
        arch = "arm64"
    elif machine in {"x86_64", "amd64"}:
        arch = "x64"
    else:
        raise RuntimeError(f"不支持自动安装 Node.js 的架构：{machine}")
    suffix = "zip" if os_name == "win" else "tar.xz"
    return f"node-{version}-{os_name}-{arch}.{suffix}"


def _run_openspec_init(openspec_bin: Path, project_root: Path, env: dict[str, str]) -> None:
    project_root.mkdir(parents=True, exist_ok=True)
    init = subprocess.run(
        [str(openspec_bin), "init", "--tools", "codex", "--profile", "core"],
        cwd=project_root,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        timeout=180,
    )
    if init.returncode == 0:
        return
    update = subprocess.run(
        [str(openspec_bin), "update"],
        cwd=project_root,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        timeout=180,
    )
    if update.returncode != 0:
        raise RuntimeError(
            "OpenSpec 初始化失败："
            f"{(init.stderr or init.stdout or update.stderr or update.stdout)[:1000]}"
        )


def _tools_dir() -> Path:
    return Path(os.environ.get("AUTODEV_TOOLS_DIR", "~/.cache/autodev/tools")).expanduser()


def _npm_prefix() -> Path:
    return _tools_dir() / "npm-global"


def _tools_bin_dir() -> Path:
    return _npm_prefix() / "bin"


def _node_install_dir() -> Path:
    return _tools_dir() / "node"


def _node_bin_dir() -> Path:
    version = os.environ.get("AUTODEV_NODE_VERSION", "v22.12.0").strip()
    archive_stem = _node_archive_name(version).removesuffix(".tar.xz").removesuffix(".zip")
    return _node_install_dir() / archive_stem / "bin"


def _project_roots() -> list[Path]:
    roots = [Path.cwd()]
    here = Path(__file__).resolve()
    roots.extend(here.parents)
    unique: list[Path] = []
    for root in roots:
        if root not in unique:
            unique.append(root)
    return unique


def _read_skill(roots: list[Path | None], skill_name: str) -> str:
    for root in roots:
        if root is None:
            continue
        for path in root.glob(f"{skill_name}*/SKILL.md"):
            return path.read_text(encoding="utf-8")
    searched = ", ".join(str(root) for root in roots if root is not None)
    raise RuntimeError(
        "未找到 OpenSpec 官方 Codex skill。请先安装并初始化："
        "npm install -g @fission-ai/openspec@latest && "
        "openspec init --tools codex --profile core；"
        f"已搜索：{searched}"
    )




def _write_change_docs(project_root: Path, docs: Mapping[str, str]) -> Path:
    change_id = _safe_change_id(str(docs.get("change_id") or "change"))
    change_dir = project_root / "openspec" / "changes" / change_id
    change_dir.mkdir(parents=True, exist_ok=True)
    (change_dir / "proposal.md").write_text(str(docs.get("proposal_md") or ""), encoding="utf-8")
    (change_dir / "design.md").write_text(str(docs.get("design_md") or ""), encoding="utf-8")
    (change_dir / "tasks.md").write_text(str(docs.get("tasks_md") or ""), encoding="utf-8")
    return change_dir


def _archive_change_docs(
    project_root: Path,
    docs: Mapping[str, str],
    archive_note: str,
) -> Path:
    change_id = _safe_change_id(str(docs.get("change_id") or "change"))
    source_dir = project_root / "openspec" / "changes" / change_id
    archive_dir = (
        project_root
        / "openspec"
        / "changes"
        / "archive"
        / f"{datetime.now(UTC).date().isoformat()}-{change_id}"
    )
    archive_dir.mkdir(parents=True, exist_ok=True)
    for filename in ("proposal.md", "design.md", "tasks.md"):
        source = source_dir / filename
        if source.exists():
            shutil.copyfile(source, archive_dir / filename)
    (archive_dir / "archive_note.md").write_text(archive_note, encoding="utf-8")
    if source_dir.exists():
        shutil.rmtree(source_dir)
    return archive_dir


def _safe_change_id(raw: str) -> str:
    normalized = raw.strip().lower().replace("_", "-").replace(" ", "-")
    safe = "".join(ch for ch in normalized if ch.isalnum() or ch == "-").strip("-")
    return safe[:96] or "change"


async def _json_llm(
    cfg: ModelConfig,
    ctx: CodingContext,
    *,
    run_name: str,
    system: str,
    user: str,
) -> dict[str, Any]:
    llm = create_llm(cfg, max_tokens=3000, json_mode=True)
    response = await retry_async(
        lambda: llm.ainvoke(
            [SystemMessage(content=system), HumanMessage(content=user)],
            config=build_trace_config(run_name, "coding", ctx, prompt_keys=[]),
        )
    )
    try:
        return json.loads(str(response.content))
    except json.JSONDecodeError:
        return {}


async def _text_llm(
    cfg: ModelConfig,
    ctx: CodingContext,
    *,
    run_name: str,
    system: str,
    user: str,
) -> str:
    llm = create_llm(cfg, max_tokens=4000)
    response = await retry_async(
        lambda: llm.ainvoke(
            [SystemMessage(content=system), HumanMessage(content=user)],
            config=build_trace_config(run_name, "coding", ctx, prompt_keys=[]),
        )
    )
    return str(response.content or "")


def _normalize_docs(raw: Mapping[str, Any]) -> dict[str, str]:
    return {
        "change_id": str(raw.get("change_id") or raw.get("id") or "change").strip()[:96],
        "proposal_md": str(raw.get("proposal_md") or raw.get("proposal") or "").strip(),
        "design_md": str(raw.get("design_md") or raw.get("design") or "").strip(),
        "tasks_md": str(raw.get("tasks_md") or raw.get("tasks") or "").strip(),
    }


def _propose_prompt(ctx: CodingContext, task: Mapping[str, Any]) -> str:
    return (
        "请按照官方 OpenSpec propose skill 为单个 coding task 生成三个核心文档。\n"
        "仅输出 JSON：change_id, proposal_md, design_md, tasks_md。\n\n"
        f"项目：{ctx.project_name}\n\n"
        f"研发/PRD/UI/评审上下文：\n{json.dumps(ctx.task_breakdown, ensure_ascii=False)[:8000]}\n\n"
        f"当前任务：\n{json.dumps(task, ensure_ascii=False)[:3000]}"
    )


def _review_prompt(ctx: CodingContext, task: Mapping[str, Any], docs: Mapping[str, str]) -> str:
    return (
        "请作为独立 OpenSpec 文档评审 Agent，评审 proposal.md、design.md、tasks.md 是否足以指导实现。\n"
        "仅输出 JSON：approved(boolean), summary(string), required_changes(string[]), issues(array)。\n\n"
        f"项目：{ctx.project_name}\n"
        f"任务：{json.dumps(task, ensure_ascii=False)[:3000]}\n"
        f"文档：{json.dumps(docs, ensure_ascii=False)[:9000]}"
    )


def _revise_prompt(
    ctx: CodingContext,
    task: Mapping[str, Any],
    docs: Mapping[str, str],
    review: Mapping[str, Any],
) -> str:
    return (
        "请按照官方 OpenSpec propose skill，根据评审意见修订三个核心文档。\n"
        "仅输出 JSON：change_id, proposal_md, design_md, tasks_md。\n\n"
        f"项目：{ctx.project_name}\n"
        f"任务：{json.dumps(task, ensure_ascii=False)[:3000]}\n"
        f"现有文档：{json.dumps(docs, ensure_ascii=False)[:7000]}\n"
        f"评审意见：{json.dumps(review, ensure_ascii=False)[:3000]}"
    )


def _apply_prompt(ctx: CodingContext, task: Mapping[str, Any], docs: Mapping[str, str]) -> str:
    return (
        "请按照官方 OpenSpec apply skill，根据已通过评审的 proposal.md、design.md、tasks.md 执行实现。\n"
        "输出实现说明和完整文件内容，供后续 synthesizer 转换为 code_files。\n\n"
        f"项目：{ctx.project_name}\n"
        f"任务：{json.dumps(task, ensure_ascii=False)[:3000]}\n"
        f"OpenSpec 文档：{json.dumps(docs, ensure_ascii=False)[:9000]}"
    )


def _archive_prompt(ctx: CodingContext, task: Mapping[str, Any], docs: Mapping[str, str]) -> str:
    return (
        "请按照官方 OpenSpec archive skill，为已完成任务生成归档说明。"
        "不要修改代码，只输出简短中文归档摘要。\n\n"
        f"项目：{ctx.project_name}\n"
        f"任务：{json.dumps(task, ensure_ascii=False)[:3000]}\n"
        f"OpenSpec 文档：{json.dumps(docs, ensure_ascii=False)[:6000]}"
    )


_OPENSPEC_REVIEW_SYSTEM = (
    "你是独立的 OpenSpec 文档评审 Agent。只审查 proposal.md、design.md、tasks.md 是否完整、"
    "一致、可执行、可验收，不编写代码。仅输出 JSON。"
)
